! BEGIN DART PREPROCESS TYPE DEFINITIONS
! UAS_U_WIND_COMPONENT,            QTY_U_WIND_COMPONENT,       COMMON_CODE
! UAS_V_WIND_COMPONENT,            QTY_V_WIND_COMPONENT,       COMMON_CODE
! UAS_TEMPERATURE,                 QTY_TEMPERATURE,            COMMON_CODE
! UAS_SPECIFIC_HUMIDITY,           QTY_SPECIFIC_HUMIDITY,      COMMON_CODE
! END DART PREPROCESS TYPE DEFINITIONS
